"""Source-grounded role template V2.

The active role contract is deliberately small: identity, status, source-backed
memories, response boundaries and unresolved claims.  Legacy persona columns
are read by older runtime code when necessary, but are never generated by this
module for new or edited roles.
"""

from __future__ import annotations

import copy
from typing import Any


ROLE_TEMPLATE_VERSION = "source_memory_v2"
ROLE_COMPACT_V2_FIELDS: tuple[str, ...] = (
    "name",
    "role_type",
    "status",
    "role_memories",
    "knowledge_ledger",
    "response_constraints",
    "unresolved_claims",
    "source_verification",
    "source_refs",
)


def _as_text(value: Any) -> str:
    return str(value or "").strip()


def _as_text_list(value: Any, *, limit: int = 0) -> list[str]:
    if isinstance(value, list):
        values = value
    elif isinstance(value, str):
        values = value.splitlines()
    else:
        values = []
    output: list[str] = []
    seen: set[str] = set()
    for item in values:
        text = _as_text(item)
        if not text or text in seen:
            continue
        seen.add(text)
        output.append(text)
        if limit and len(output) >= limit:
            break
    return output


def _normalize_source_refs(value: Any) -> list[dict[str, Any]]:
    return [copy.deepcopy(item) for item in value if isinstance(item, dict)] if isinstance(value, list) else []


def _normalize_role_memories(person: dict[str, Any] | None) -> list[dict[str, Any]]:
    person = person or {}
    explicit = person.get("role_memories")
    rows = explicit if isinstance(explicit, list) else []
    if not rows:
        # Read legacy ledgers only as a one-way migration source.  The result is
        # stored as role_memories and never expands back to persona labels.
        ledger = person.get("knowledge_ledger") if isinstance(person.get("knowledge_ledger"), list) else []
        rows = [
            {
                "memory_id": item.get("knowledge_id"),
                "memory_type": item.get("knowledge_mode"),
                "statement": item.get("content"),
                "certainty": item.get("certainty"),
                "source_refs": item.get("source_refs"),
                "event_id": item.get("claim_id"),
            }
            for item in ledger
            if isinstance(item, dict)
        ]
    normalized: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for index, item in enumerate(rows, start=1):
        if not isinstance(item, dict):
            continue
        statement = _as_text(item.get("statement") or item.get("content"))
        if not statement:
            continue
        row = {
            "memory_id": _as_text(item.get("memory_id")) or f"M{index}",
            "memory_type": _as_text(item.get("memory_type") or item.get("knowledge_mode")) or "source_mention",
            "statement": statement,
            "quote": _as_text(item.get("quote")),
            "time_hint": _as_text(item.get("time_hint")),
            "place_hint": _as_text(item.get("place_hint")),
            "actors": _as_text_list(item.get("actors")),
            "certainty": _as_text(item.get("certainty")) or "source_supported",
            "source_refs": _normalize_source_refs(item.get("source_refs")),
            "event_id": _as_text(item.get("event_id") or item.get("claim_id")),
        }
        fingerprint = (row["statement"], str((row["source_refs"] or [{}])[0].get("start", "")))
        if fingerprint in seen:
            continue
        seen.add(fingerprint)
        normalized.append(row)
    return normalized


def _normalize_ledger(memories: list[dict[str, Any]], person: dict[str, Any] | None = None) -> list[dict[str, Any]]:
    if memories:
        return [
            {
                "knowledge_id": item["memory_id"],
                "claim_id": item.get("event_id", ""),
                "knowledge_mode": item.get("memory_type", "source_mention"),
                "content": item["statement"],
                "certainty": item.get("certainty", "source_supported"),
                "disclosure_policy": "answer_when_asked",
                "verbalization": item["statement"],
                "source_refs": copy.deepcopy(item.get("source_refs") or []),
            }
            for item in memories
        ]
    # Preserve legacy knowledge as source material when editing an old case.
    person = person or {}
    output: list[dict[str, Any]] = []
    for key, mode, policy in (
        ("known_key_points", "known", "answer_when_asked"),
        ("knows_facts", "known", "answer_when_asked"),
        ("withheld_key_points", "withheld", "withhold_until_triggered"),
        ("hidden_truths", "withheld", "withhold_until_triggered"),
        ("does_not_know", "unknown", "must_not_assert"),
        ("cannot_answer", "unknown", "must_not_assert"),
    ):
        for content in _as_text_list(person.get(key)):
            if any(item.get("content") == content for item in output):
                continue
            output.append({
                "knowledge_id": f"K{len(output) + 1}",
                "claim_id": "",
                "knowledge_mode": mode,
                "content": content,
                "certainty": "legacy_config",
                "disclosure_policy": policy,
                "verbalization": content,
                "source_refs": [],
            })
    return output


def person_to_role_compact_view(person: dict[str, Any] | None, *, scene_behavior_mode: str = "") -> dict[str, Any]:
    person = copy.deepcopy(person or {})
    memories = _normalize_role_memories(person)
    ledger = _normalize_ledger(memories, person)
    return {
        "name": _as_text(person.get("name")),
        "role_type": _as_text(person.get("role_type") or person.get("role")) or "相关人员",
        "status": _as_text(person.get("status")) or "正常",
        "role_memories": memories,
        "knowledge_ledger": ledger,
        "response_constraints": _as_text_list(person.get("response_constraints"), limit=12),
        "unresolved_claims": copy.deepcopy(person.get("unresolved_claims")) if isinstance(person.get("unresolved_claims"), list) else [],
        "source_verification": _as_text(person.get("source_verification")),
        "source_refs": _normalize_source_refs(person.get("source_refs")),
        "role_template_version": ROLE_TEMPLATE_VERSION,
        "persona_autofill": False,
    }


def expand_role_compact_to_person(compact: dict[str, Any] | None, *, scene_behavior_mode: str = "") -> dict[str, Any]:
    compact = copy.deepcopy(compact or {})
    memories = _normalize_role_memories(compact)
    ledger = _normalize_ledger(memories, compact)
    return {
        "person_id": _as_text(compact.get("person_id")),
        "name": _as_text(compact.get("name")),
        "aliases": _as_text_list(compact.get("aliases")),
        "role": _as_text(compact.get("role") or compact.get("role_type")) or "相关人员",
        "role_type": _as_text(compact.get("role_type") or compact.get("role")) or "相关人员",
        "status": _as_text(compact.get("status")) or "正常",
        "role_memories": memories,
        "knowledge_ledger": ledger,
        "response_constraints": _as_text_list(compact.get("response_constraints"), limit=12),
        "unresolved_claims": copy.deepcopy(compact.get("unresolved_claims")) if isinstance(compact.get("unresolved_claims"), list) else [],
        "source_verification": _as_text(compact.get("source_verification")),
        "source_refs": _normalize_source_refs(compact.get("source_refs")),
        "persona_source": "source_grounded_role_memory",
        "persona_contract_version": ROLE_TEMPLATE_VERSION,
        "role_template_version": ROLE_TEMPLATE_VERSION,
        "persona_autofill": False,
    }
