"""Shared prompt modules, guardrails, and case-pipeline prompts."""

from .assessment_point import ASSESSMENT_POINT_PROMPT
from .case_pipeline import (
    COMPLETE_CASE_STORY_PROMPT,
    FACTS_ROLES_MEMORIES_PROMPT,
    OPENING_DIALOGUE_ADDENDUM,
    SCENE_BLUEPRINT_PROMPT,
    build_opening_system_prompt,
)
from .guardrails import (
    ADMIN_JSON_GUARDRAILS,
    COACH_SPEECH_GUARDRAILS,
    DIALOGUE_ROLE_GUARDRAILS,
    DIRECTOR_GUARDRAILS,
    EVALUATION_GUARDRAILS,
)
from .training_dialogue import SYSTEM_PROMPT_TEMPLATE

__all__ = [
    "ASSESSMENT_POINT_PROMPT",
    "COMPLETE_CASE_STORY_PROMPT",
    "FACTS_ROLES_MEMORIES_PROMPT",
    "OPENING_DIALOGUE_ADDENDUM",
    "SCENE_BLUEPRINT_PROMPT",
    "SYSTEM_PROMPT_TEMPLATE",
    "build_opening_system_prompt",
    "ADMIN_JSON_GUARDRAILS",
    "COACH_SPEECH_GUARDRAILS",
    "DIALOGUE_ROLE_GUARDRAILS",
    "DIRECTOR_GUARDRAILS",
    "EVALUATION_GUARDRAILS",
]
