from .assessment_point_officer import (
    ASSESSMENT_POINT_OFFICER_ROLE,
    ASSESSMENT_POINT_OFFICER_SYSTEM_PROMPT,
    ASSESSMENT_POINT_OFFICER_USER_TEMPLATE,
)
from .training_voice_layers import TRAINING_VOICE_LAYER_PROMPT

__all__ = [
    "TRAINING_VOICE_LAYER_PROMPT",
    "ASSESSMENT_POINT_OFFICER_ROLE",
    "ASSESSMENT_POINT_OFFICER_SYSTEM_PROMPT",
    "ASSESSMENT_POINT_OFFICER_USER_TEMPLATE",
]
